using FluentAssertions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading.Tasks;
using WorkSessionTrackerAPI.Authorization;
using WorkSessionTrackerAPI.Data;
using WorkSessionTrackerAPI.Models;
using WorkSessionTrackerAPI.Models.Enums;

namespace WorkSessionTrackerAPI.UnitTests.Authorization
{
    public class CommentAuthorizationHandlerTests
    {
        private async Task<ApplicationDbContext> GetDbContext()
        {
            var options = new DbContextOptionsBuilder<ApplicationDbContext>()
                .UseInMemoryDatabase(databaseName: Guid.NewGuid().ToString())
                .Options;
            var dbContext = new ApplicationDbContext(options);
            await dbContext.Database.EnsureCreatedAsync();
            return dbContext;
        }

        private ClaimsPrincipal CreateUser(string id, string role)
        {
            var claims = new List<Claim>
            {
                new Claim(ClaimTypes.NameIdentifier, id),
                new Claim(ClaimTypes.Role, role)
            };
            var identity = new ClaimsIdentity(claims, "TestAuth");
            return new ClaimsPrincipal(identity);
        }

        private async Task<(int studentId, int companyId, int commentId)> SeedData(ApplicationDbContext dbContext)
        {
            var company = new Company { Name = "Test Inc." };
            var student = new Student { Name = "Test Student", Company = company, Email = "student@test.com", UserName = "student@test.com" };
            var workSession = new WorkSession { Student = student, StartDateTime = DateTime.UtcNow, EndDateTime = DateTime.UtcNow.AddHours(1) };
            var comment = new Comment { WorkSession = workSession, Content = "Test comment" };

            // By using the generic DbContext.Add method on the top-level entity,
            // EF Core's change tracker will automatically discover and add the related
            // company, student, and work session without needing specific DbSet properties.
            dbContext.Add(comment);
            await dbContext.SaveChangesAsync();

            // The Ids are now generated by the in-memory database provider.
            return (student.Id, company.Id, comment.Id);
        }

        [Fact]
        public async Task HandleAsync_ShouldSucceed_WhenUserIsAdmin()
        {
            // Arrange
            var dbContext = await GetDbContext();
            var (_, _, commentId) = await SeedData(dbContext);
            var handler = new CommentAuthorizationHandler(dbContext);
            var requirement = new CanCommentOnWorkSessionRequirement();
            var adminUser = CreateUser("99", UserRoleEnum.Admin.ToString());
            var comment = await dbContext.Comments.FindAsync(commentId);
            var context = new AuthorizationHandlerContext(new[] { requirement }, adminUser, comment);

            // Act
            await handler.HandleAsync(context);

            // Assert
            context.HasSucceeded.Should().BeTrue();
        }

        [Fact]
        public async Task HandleAsync_ShouldFail_WhenStudentAccessesAnotherStudentsComment()
        {
            // Arrange
            var dbContext = await GetDbContext();
            var (_, _, commentId) = await SeedData(dbContext); // Belongs to student 1
            var handler = new CommentAuthorizationHandler(dbContext);
            var requirement = new CanCommentOnWorkSessionRequirement();
            var otherStudentId = 2;
            var requestingStudent = CreateUser(otherStudentId.ToString(), UserRoleEnum.Student.ToString());
            var comment = await dbContext.Comments.FindAsync(commentId);
            var context = new AuthorizationHandlerContext(new[] { requirement }, requestingStudent, comment);

            // Act
            await handler.HandleAsync(context);

            // Assert
            context.HasSucceeded.Should().BeFalse();
        }

        [Fact]
        public async Task HandleAsync_ShouldFail_WhenCompanyAccessesUnrelatedStudentsComment()
        {
            // Arrange
            var dbContext = await GetDbContext();
            var (_, _, commentId) = await SeedData(dbContext); // Belongs to student of company 1
            var handler = new CommentAuthorizationHandler(dbContext);
            var requirement = new CanViewCommentRequirement();
            var otherCompanyId = 99;
            var companyUser = CreateUser(otherCompanyId.ToString(), UserRoleEnum.Company.ToString());
            var comment = await dbContext.Comments.FindAsync(commentId);
            var context = new AuthorizationHandlerContext(new[] { requirement }, companyUser, comment);

            // Act
            await handler.HandleAsync(context);

            // Assert
            context.HasSucceeded.Should().BeFalse();
        }

        [Fact]
        public async Task HandleAsync_ShouldFail_WhenResourceIsNull()
        {
            // Arrange
            var dbContext = await GetDbContext();
            var handler = new CommentAuthorizationHandler(dbContext);
            var requirement = new CanCommentOnWorkSessionRequirement();
            var studentUser = CreateUser("1", UserRoleEnum.Student.ToString()); // Any authenticated user
            var context = new AuthorizationHandlerContext(new[] { requirement }, studentUser, null);

            // Act
            await handler.HandleAsync(context);

            // Assert
            context.HasSucceeded.Should().BeFalse();
        }
    }
}
