// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkSessionTrackerAPI.Data;

#nullable disable

namespace WorkSessionTrackerAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251207173007_Reset")]
    partial class Reset
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WorkSessionTrackerAPI.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SupervisorId")
                        .HasColumnType("int");

                    b.Property<int>("WorkSessionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SupervisorId");

                    b.HasIndex("WorkSessionId")
                        .IsUnique();

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("WorkSessionTrackerAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailVerificationToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EmailVerificationTokenExpiration")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasDiscriminator<string>("UserType").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("WorkSessionTrackerAPI.Models.WorkSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Verified")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("WorkSessions");
                });

            modelBuilder.Entity("WorkSessionTrackerAPI.Models.Employee", b =>
                {
                    b.HasBaseType("WorkSessionTrackerAPI.Models.User");

                    b.Property<int?>("SupervisorId")
                        .HasColumnType("int");

                    b.HasIndex("SupervisorId");

                    b.HasDiscriminator().HasValue("Employee");
                });

            modelBuilder.Entity("WorkSessionTrackerAPI.Models.Supervisor", b =>
                {
                    b.HasBaseType("WorkSessionTrackerAPI.Models.User");

                    b.Property<string>("TotpSeed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Supervisor");
                });

            modelBuilder.Entity("WorkSessionTrackerAPI.Models.Comment", b =>
                {
                    b.HasOne("WorkSessionTrackerAPI.Models.Supervisor", "Supervisor")
                        .WithMany("Comments")
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WorkSessionTrackerAPI.Models.WorkSession", "WorkSession")
                        .WithOne("Comment")
                        .HasForeignKey("WorkSessionTrackerAPI.Models.Comment", "WorkSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supervisor");

                    b.Navigation("WorkSession");
                });

            modelBuilder.Entity("WorkSessionTrackerAPI.Models.WorkSession", b =>
                {
                    b.HasOne("WorkSessionTrackerAPI.Models.Employee", "Employee")
                        .WithMany("WorkSessions")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("WorkSessionTrackerAPI.Models.Employee", b =>
                {
                    b.HasOne("WorkSessionTrackerAPI.Models.Supervisor", "Supervisor")
                        .WithMany("Employees")
                        .HasForeignKey("SupervisorId");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("WorkSessionTrackerAPI.Models.WorkSession", b =>
                {
                    b.Navigation("Comment");
                });

            modelBuilder.Entity("WorkSessionTrackerAPI.Models.Employee", b =>
                {
                    b.Navigation("WorkSessions");
                });

            modelBuilder.Entity("WorkSessionTrackerAPI.Models.Supervisor", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
